[[news]]
date = "2026-06"
content = "My undergraduate thesis was selected as an Outstanding Thesis (top ~3%)."

[[news]]
date = "2026-05"
content = "Released PrefBench as an arXiv preprint."

[[news]]
date = "2026-04"
content = "I will join Johns Hopkins University as an M.S.E. student in Computer Science in Fall 2026."

[[news]]
date = "2026-03"
content = "Released Draft-and-Target Sampling for Video Generation Policy as an arXiv preprint."

[[news]]
date = "2025-04"
content = "Our work on test-time training for 4D medical image interpolation was accepted to IJCNN 2025 as an oral presentation."
